#!/bin/bash

dir=$1

function br() {
  echo
  echo ----
  echo
}

br

for file in $(find $dir/* -type f)
do
  $file
done

br

find $dir/* -type f |
while read file
do
  $file
done

br

find $dir/* -type f |
while read file
do
  bash -c "$(pwd)/$file" &
  wait $!
done

br
